### ISSUE TITLE
Issue with enabled extention on Fedora 40

### ISSUE THREAD

**Issue by zakian** [tzawezin/gnome-ddc-brightness-contrast-extra-dimming#2]
Hello.
There is a problem in Fedora 40 (Gnome 46) . When the extension is active, it is impossible to move workspaces and move open applications between them via drag'n'drop.

<details>
  <summary>Screenshot</summary>

  ![image](https://github.com/user-attachments/assets/22060f3e-55cc-4bf3-9d96-3b940d03553a)
</details>

**Comment by tzawezin** [comment]
hello,
Thank u for posting the issue,
the problem seem to come from the extra dimming black overlay.
While i look into resolving the problem u can temporary fix it by disabling the overlay, so u can still use it to control the screen brightness and contrast.

in the file: 
~/.local/share/gnome-shell/extensions/ddc-brightness-contrast-extra-dimming@tzawezin.github.io/extension.js

comment out line (95 or 97) and it seems to work again:
 "                  newOverlaySlider(display);"                   =>   "                  //newOverlaySlider(display);" 

also comment out lines (177 to 179 or 178 to 180) so it does not give an error while disabling the extension:
"                d.overlay.set_opacity(0);"                                 "                //d.overlay.set_opacity(0);"    
"                Main.uiGroup.remove_actor(d.overlay);"  =>   "                //Main.uiGroup.remove_actor(d.overlay);" 
"                d.overlay.destroy();"                                         "                //d.overlay.destroy();"  

I hope this helps for now and I'll update when the problem is resolved.

**Comment by zakian** [comment]
Hello
Yes, it fixed it. Everything looks fine. Сhanging the brightness and contrast works. Drag'n'dron applications between workspaces also works. Thank you very much for your assistance and your work.

**Comment by tzawezin** [comment]
Sorry for the delay but I updated the extension that the overlay gets hidden when the overview is showing, so u can drag'n'drop and add extra dimming when the overview is closed.
It is currently waiting for review  (version 15/16) and will soon be available (or u can copy the "extension.js" of your gnome version already).
Happy to assist and thank you again for posting the issue and using the extension.

**Comment by spbisc97** [comment]
Hi, i still have troubles with gnome 40: I have this error

Mar 16 16:49:53 gossip-fed gnome-shell[4268]: Exception in callback for signal: hiding: TypeError: Main.uiGroup.add_actor is not a function
                                              
                                              Stack trace:
                                                _onOverviewHiding/<@file:///home/simone/.local/share/gnome-shell/extensions/ddc-brightness-contrast-extra-dimming@tzawezin.github.io/extension.js:183:48
                                                _onOverviewHiding@file:///home/simone/.local/share/gnome-shell/extensions/ddc-brightness-contrast-extra-dimming@tzawezin.github.io/extension.js:183:22
                                                _callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
                                                _emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
                                                _changeShownState@resource:///org/gnome/shell/ui/overview.js:305:14
                                                _animateNotVisible@resource:///org/gnome/shell/ui/overview.js:626:14
                                                hide@resource:///org/gnome/shell/ui/overview.js:610:14
                                                toggle@resource:///org/gnome/shell/ui/overview.js:655:18
                                                _init/<@resource:///org/gnome/shell/ui/overviewControls.js:449:31
                                                @resource:///org/gnome/shell/ui/init.js:21:20
